spring.application.name=ai
spring.datasource.url=jdbc:mysql://localhost:3306/ai
spring.datasource.username=root
spring.datasource.password=Crystal@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

my.api.key=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
server.port=${PORT:8080}